# docker-compose.pc3.yml
# PC3 - ACTOR DE RENOVACIÓN (Virtual 2)
# IP PC1 configurada: 192.168.10.12
# IP PC3 (win102): 192.168.0.9
#
# Este PC ejecuta:
# - Actor Renovación

services:
  # Actor de Renovación
  actor_renovacion:
    build:
      context: .
      dockerfile: ./actor_renovacion/Dockerfile
    container_name: actor_renovacion_pc3
    environment:
      - GESTOR_CARGA_PUB_ADDR=tcp://192.168.10.12:5556
      - GESTOR_ALMACENAMIENTO_HOST=192.168.10.12
      - GESTOR_ALMACENAMIENTO_PORT=5570
    extra_hosts:
      - "gestor_carga:192.168.10.12"
      - "gestor_almacenamiento:192.168.10.12"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
